In [2]:
import numpy as np
import time 

In [3]:
x = np.random.random(100000000)
start= time.time()
sum(x)/len(x)
print(time.time()-start) # time taken to calculate mean without numpy

25.902758598327637


In [4]:
start=time.time()
np.mean(x)
print(time.time()-start)

0.25348567962646484


In [5]:
y= np.array([1,2,3,4,5])
print (y)
print(y.shape)
print(y.dtype)

[1 2 3 4 5]
(5,)
int32


In [6]:
z = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print (z)
print("Shape =",z.shape)
print("dtype =",z.dtype)
print("Size = ",z.size)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape = (4, 3)
dtype = int32
Size =  12


In [7]:
np.save("myarray",z)

In [8]:
zz = np.load("myarray.npy")
print(zz)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
x = np.zeros((4,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
x = np.ones((4,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
x = np.full((4,5),7)
print(x)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [12]:
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
x = np.diag([4,6,8,3])
print(x)

[[4 0 0 0]
 [0 6 0 0]
 [0 0 8 0]
 [0 0 0 3]]


In [14]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
x = np.arange(3,10)
print(x)

[3 4 5 6 7 8 9]


In [16]:
x = np.arange(1,10,2)
print(x)

[1 3 5 7 9]


In [17]:
x = np.linspace(0,30,10,endpoint=False)
print(x)

[ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27.]


In [18]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [19]:
x= np.reshape(x,(4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [20]:
x= np.random.random((3,3))
print(x)

[[0.13592297 0.01559567 0.52041862]
 [0.60521939 0.15368471 0.35233457]
 [0.32125464 0.36885575 0.23678056]]


In [21]:
x= np.random.randint(4,20,(3,2))
print(x)

[[14 15]
 [13 17]
 [19 12]]


In [22]:
x = np.arange(10)
print(x)
print("1st element = ",x[0])   # numpy indices 
print("3rd element = ",x[2])
print("5th element = ",x[4])

[0 1 2 3 4 5 6 7 8 9]
1st element =  0
3rd element =  2
5th element =  4


In [23]:
x = np.arange(20).reshape(4,5)
print(x)
print("element at (0,0) : ",x[0,0])   # numpy indices 
print("element at (2,3) : ",x[2,3])
print("element at (3,3): ",x[3,3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
element at (0,0) :  0
element at (2,3) :  13
element at (3,3):  18


In [24]:
x[0,0]=100
print(x)

[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]


In [25]:
x = np.arange(10)
print(x)
x= np.delete(x, 1,axis=0)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[0 2 3 4 5 6 7 8 9]


In [26]:
x = np.arange(10)
print(x)
x= np.append(x,[11,12])
print(x)
x = x.reshape(4,3)
print(x)
x= np.append(x,[[1],[1],[1],[1]],axis=1)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 11 12]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 11 12]]
[[ 0  1  2  1]
 [ 3  4  5  1]
 [ 6  7  8  1]
 [ 9 11 12  1]]


In [27]:
x = np.array([1,2])
print(x)

[1 2]


In [28]:
y = np.array([[3,4],[5,6]])
print(y)

[[3 4]
 [5 6]]


In [29]:
z=np.vstack((x,y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [30]:
w= np.hstack((y,x.reshape(2,1)))
print(w)

[[3 4 1]
 [5 6 2]]


In [35]:
w_colmean=w.std(axis=0)
print(w_colmean)
w_colmean.shape

[1.  1.  0.5]


(3,)

In [38]:
x = np.random.randint(0,5001,size=(1000,20))
print(x.shape)

(1000, 20)


In [39]:
ave_cols=x.mean(axis=0)
std_cols=x.std(axis=0)

In [42]:
print(ave_cols.shape)
print(std_cols.shape)

(20,)
(20,)


In [43]:
x_norm=(x-ave_cols)/std_cols

In [44]:
print(x_norm.mean())

1.1723955140041653e-17


In [45]:
row_indices=np.random.permutation(x_norm.shape)